### ISSUE TITLE
Arg_NotSupportedException when calling executor.Reset()

### ISSUE THREAD

**Issue by GeorgeFence** [ascpixi/cosmos-coroutines#3]
title
![image](https://github.com/ascpixi/cosmos-coroutines/assets/105986123/5cc7d0d3-99ab-4d4f-b049-be3718a612b2)

**Comment by GeorgeFence** [comment]
Code: internal void Step()
        {
            try
            {
                ExecutionEnded = !executor.MoveNext();
                if(ExecutionEnded)
                {
                    executor.Reset();
                    executor.MoveNext();
                }
            }
            catch(Exception ex)
            {
                SYS32.KernelPanic(ex, "Coroutine");
            }
        }

**Comment by GeorgeFence** [comment]
@ascpixi @zarlo

**Comment by ascpixi** [comment]
It looks like you're inheriting a class from `Coroutine`. You shouldn't really do that - what are you trying to achieve?

**Comment by GeorgeFence** [comment]
i'm trying to make repetative tasks

**Comment by ascpixi** [comment]
What do you mean by "repetitive tasks"? If you simply want to start multiple coroutines that run in infinite loops, please refer to the README file. Here's an example:
```cs
var coroutine = new Coroutine(MyCoroutine1());
coroutine.Start(); // will run the coroutine on the main pool; to run it in another, use CoroutinePool.AddCoroutine

// ...

IEnumerator<CoroutineControlPoint> MyCoroutine1()
{
    while(true) {
        Console.WriteLine("This prints every second.");
        yield return WaitFor.Seconds(1);
    }
}
```

More details are in the README file. Please be sure to `yield return` in order to return control back to the scheduler. You shouldn't inherit any class other than `CoroutineControlPoint`.

**Comment by GeorgeFence** [comment]
oh thanks
